//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the proc_control package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __proc_control__PID4AXISCONFIG_H__
#define __proc_control__PID4AXISCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace proc_control
{
  class PID4AxisConfigStatics;
  
  class PID4AxisConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(PID4AxisConfig &config, const PID4AxisConfig &max, const PID4AxisConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PID4AxisConfig &config1, const PID4AxisConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PID4AxisConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PID4AxisConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PID4AxisConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PID4AxisConfig &config) const = 0;
      virtual void getValue(const PID4AxisConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T PID4AxisConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (PID4AxisConfig::* field);

      virtual void clamp(PID4AxisConfig &config, const PID4AxisConfig &max, const PID4AxisConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PID4AxisConfig &config1, const PID4AxisConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PID4AxisConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PID4AxisConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PID4AxisConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PID4AxisConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PID4AxisConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PID4AxisConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PID4AxisConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<PID4AxisConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PID4AxisConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("CONSTANT_DEPTH_FORCE"==(*_i)->name){CONSTANT_DEPTH_FORCE = boost::any_cast<double>(val);}
        if("X_P"==(*_i)->name){X_P = boost::any_cast<double>(val);}
        if("X_I"==(*_i)->name){X_I = boost::any_cast<double>(val);}
        if("X_D"==(*_i)->name){X_D = boost::any_cast<double>(val);}
        if("X_I_LIMIT"==(*_i)->name){X_I_LIMIT = boost::any_cast<double>(val);}
        if("X_MIN_ACTUATION"==(*_i)->name){X_MIN_ACTUATION = boost::any_cast<double>(val);}
        if("X_MAX_ACTUATION"==(*_i)->name){X_MAX_ACTUATION = boost::any_cast<double>(val);}
        if("Y_P"==(*_i)->name){Y_P = boost::any_cast<double>(val);}
        if("Y_I"==(*_i)->name){Y_I = boost::any_cast<double>(val);}
        if("Y_D"==(*_i)->name){Y_D = boost::any_cast<double>(val);}
        if("Y_I_LIMIT"==(*_i)->name){Y_I_LIMIT = boost::any_cast<double>(val);}
        if("Y_MIN_ACTUATION"==(*_i)->name){Y_MIN_ACTUATION = boost::any_cast<double>(val);}
        if("Y_MAX_ACTUATION"==(*_i)->name){Y_MAX_ACTUATION = boost::any_cast<double>(val);}
        if("Z_P"==(*_i)->name){Z_P = boost::any_cast<double>(val);}
        if("Z_I"==(*_i)->name){Z_I = boost::any_cast<double>(val);}
        if("Z_D"==(*_i)->name){Z_D = boost::any_cast<double>(val);}
        if("Z_I_LIMIT"==(*_i)->name){Z_I_LIMIT = boost::any_cast<double>(val);}
        if("Z_MIN_ACTUATION"==(*_i)->name){Z_MIN_ACTUATION = boost::any_cast<double>(val);}
        if("Z_MAX_ACTUATION"==(*_i)->name){Z_MAX_ACTUATION = boost::any_cast<double>(val);}
        if("YAW_P"==(*_i)->name){YAW_P = boost::any_cast<double>(val);}
        if("YAW_I"==(*_i)->name){YAW_I = boost::any_cast<double>(val);}
        if("YAW_D"==(*_i)->name){YAW_D = boost::any_cast<double>(val);}
        if("YAW_I_LIMIT"==(*_i)->name){YAW_I_LIMIT = boost::any_cast<double>(val);}
        if("YAW_MIN_ACTUATION"==(*_i)->name){YAW_MIN_ACTUATION = boost::any_cast<double>(val);}
        if("YAW_MAX_ACTUATION"==(*_i)->name){YAW_MAX_ACTUATION = boost::any_cast<double>(val);}
      }
    }

    double CONSTANT_DEPTH_FORCE;
double X_P;
double X_I;
double X_D;
double X_I_LIMIT;
double X_MIN_ACTUATION;
double X_MAX_ACTUATION;
double Y_P;
double Y_I;
double Y_D;
double Y_I_LIMIT;
double Y_MIN_ACTUATION;
double Y_MAX_ACTUATION;
double Z_P;
double Z_I;
double Z_D;
double Z_I_LIMIT;
double Z_MIN_ACTUATION;
double Z_MAX_ACTUATION;
double YAW_P;
double YAW_I;
double YAW_D;
double YAW_I_LIMIT;
double YAW_MIN_ACTUATION;
double YAW_MAX_ACTUATION;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double CONSTANT_DEPTH_FORCE;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double X_P;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double X_I;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double X_D;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double X_I_LIMIT;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double X_MIN_ACTUATION;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double X_MAX_ACTUATION;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Y_P;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Y_I;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Y_D;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Y_I_LIMIT;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Y_MIN_ACTUATION;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Y_MAX_ACTUATION;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Z_P;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Z_I;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Z_D;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Z_I_LIMIT;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Z_MIN_ACTUATION;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Z_MAX_ACTUATION;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double YAW_P;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double YAW_I;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double YAW_D;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double YAW_I_LIMIT;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double YAW_MIN_ACTUATION;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double YAW_MAX_ACTUATION;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PID4AxisConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PID4AxisConfig &__max__ = __getMax__();
      const PID4AxisConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PID4AxisConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PID4AxisConfig &__getDefault__();
    static const PID4AxisConfig &__getMax__();
    static const PID4AxisConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const PID4AxisConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void PID4AxisConfig::ParamDescription<std::string>::clamp(PID4AxisConfig &config, const PID4AxisConfig &max, const PID4AxisConfig &min) const
  {
    return;
  }

  class PID4AxisConfigStatics
  {
    friend class PID4AxisConfig;
    
    PID4AxisConfigStatics()
    {
PID4AxisConfig::GroupDescription<PID4AxisConfig::DEFAULT, PID4AxisConfig> Default("Default", "", 0, 0, true, &PID4AxisConfig::groups);
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.CONSTANT_DEPTH_FORCE = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.CONSTANT_DEPTH_FORCE = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.CONSTANT_DEPTH_FORCE = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("CONSTANT_DEPTH_FORCE", "double", 0, "Constant effort to keep the submarine depth", "", &PID4AxisConfig::CONSTANT_DEPTH_FORCE)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("CONSTANT_DEPTH_FORCE", "double", 0, "Constant effort to keep the submarine depth", "", &PID4AxisConfig::CONSTANT_DEPTH_FORCE)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.X_P = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.X_P = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.X_P = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_P", "double", 0, "X: The proportional coefficient", "", &PID4AxisConfig::X_P)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_P", "double", 0, "X: The proportional coefficient", "", &PID4AxisConfig::X_P)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.X_I = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.X_I = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.X_I = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_I", "double", 0, "X: The integration coefficient", "", &PID4AxisConfig::X_I)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_I", "double", 0, "X: The integration coefficient", "", &PID4AxisConfig::X_I)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.X_D = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.X_D = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.X_D = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_D", "double", 0, "X: The derivative coefficient", "", &PID4AxisConfig::X_D)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_D", "double", 0, "X: The derivative coefficient", "", &PID4AxisConfig::X_D)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.X_I_LIMIT = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.X_I_LIMIT = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.X_I_LIMIT = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_I_LIMIT", "double", 0, "X: Maximum integration", "", &PID4AxisConfig::X_I_LIMIT)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_I_LIMIT", "double", 0, "X: Maximum integration", "", &PID4AxisConfig::X_I_LIMIT)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.X_MIN_ACTUATION = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.X_MIN_ACTUATION = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.X_MIN_ACTUATION = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_MIN_ACTUATION", "double", 0, "X: Minimum actuation", "", &PID4AxisConfig::X_MIN_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_MIN_ACTUATION", "double", 0, "X: Minimum actuation", "", &PID4AxisConfig::X_MIN_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.X_MAX_ACTUATION = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.X_MAX_ACTUATION = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.X_MAX_ACTUATION = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_MAX_ACTUATION", "double", 0, "X: Maximum actuation", "", &PID4AxisConfig::X_MAX_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("X_MAX_ACTUATION", "double", 0, "X: Maximum actuation", "", &PID4AxisConfig::X_MAX_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Y_P = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Y_P = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Y_P = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_P", "double", 0, "Y: The proportional coefficient", "", &PID4AxisConfig::Y_P)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_P", "double", 0, "Y: The proportional coefficient", "", &PID4AxisConfig::Y_P)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Y_I = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Y_I = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Y_I = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_I", "double", 0, "Y: The integration coefficient", "", &PID4AxisConfig::Y_I)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_I", "double", 0, "Y: The integration coefficient", "", &PID4AxisConfig::Y_I)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Y_D = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Y_D = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Y_D = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_D", "double", 0, "Y: The derivative coefficient", "", &PID4AxisConfig::Y_D)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_D", "double", 0, "Y: The derivative coefficient", "", &PID4AxisConfig::Y_D)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Y_I_LIMIT = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Y_I_LIMIT = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Y_I_LIMIT = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_I_LIMIT", "double", 0, "Y: Maximum integration", "", &PID4AxisConfig::Y_I_LIMIT)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_I_LIMIT", "double", 0, "Y: Maximum integration", "", &PID4AxisConfig::Y_I_LIMIT)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Y_MIN_ACTUATION = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Y_MIN_ACTUATION = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Y_MIN_ACTUATION = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_MIN_ACTUATION", "double", 0, "Y: Minimum actuation", "", &PID4AxisConfig::Y_MIN_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_MIN_ACTUATION", "double", 0, "Y: Minimum actuation", "", &PID4AxisConfig::Y_MIN_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Y_MAX_ACTUATION = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Y_MAX_ACTUATION = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Y_MAX_ACTUATION = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_MAX_ACTUATION", "double", 0, "Y: Maximum actuation", "", &PID4AxisConfig::Y_MAX_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Y_MAX_ACTUATION", "double", 0, "Y: Maximum actuation", "", &PID4AxisConfig::Y_MAX_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Z_P = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Z_P = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Z_P = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_P", "double", 0, "Z: The proportional coefficient", "", &PID4AxisConfig::Z_P)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_P", "double", 0, "Z: The proportional coefficient", "", &PID4AxisConfig::Z_P)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Z_I = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Z_I = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Z_I = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_I", "double", 0, "Z: The integration coefficient", "", &PID4AxisConfig::Z_I)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_I", "double", 0, "Z: The integration coefficient", "", &PID4AxisConfig::Z_I)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Z_D = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Z_D = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Z_D = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_D", "double", 0, "Z: The derivative coefficient", "", &PID4AxisConfig::Z_D)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_D", "double", 0, "Z: The derivative coefficient", "", &PID4AxisConfig::Z_D)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Z_I_LIMIT = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Z_I_LIMIT = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Z_I_LIMIT = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_I_LIMIT", "double", 0, "Z: Maximum integration", "", &PID4AxisConfig::Z_I_LIMIT)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_I_LIMIT", "double", 0, "Z: Maximum integration", "", &PID4AxisConfig::Z_I_LIMIT)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Z_MIN_ACTUATION = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Z_MIN_ACTUATION = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Z_MIN_ACTUATION = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_MIN_ACTUATION", "double", 0, "Z: Minimum actuation", "", &PID4AxisConfig::Z_MIN_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_MIN_ACTUATION", "double", 0, "Z: Minimum actuation", "", &PID4AxisConfig::Z_MIN_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Z_MAX_ACTUATION = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Z_MAX_ACTUATION = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Z_MAX_ACTUATION = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_MAX_ACTUATION", "double", 0, "Z: Maximum actuation", "", &PID4AxisConfig::Z_MAX_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("Z_MAX_ACTUATION", "double", 0, "Z: Maximum actuation", "", &PID4AxisConfig::Z_MAX_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.YAW_P = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.YAW_P = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.YAW_P = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_P", "double", 0, "YAW: The proportional coefficient", "", &PID4AxisConfig::YAW_P)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_P", "double", 0, "YAW: The proportional coefficient", "", &PID4AxisConfig::YAW_P)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.YAW_I = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.YAW_I = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.YAW_I = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_I", "double", 0, "YAW: The integration coefficient", "", &PID4AxisConfig::YAW_I)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_I", "double", 0, "YAW: The integration coefficient", "", &PID4AxisConfig::YAW_I)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.YAW_D = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.YAW_D = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.YAW_D = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_D", "double", 0, "YAW: The derivative coefficient", "", &PID4AxisConfig::YAW_D)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_D", "double", 0, "YAW: The derivative coefficient", "", &PID4AxisConfig::YAW_D)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.YAW_I_LIMIT = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.YAW_I_LIMIT = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.YAW_I_LIMIT = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_I_LIMIT", "double", 0, "YAW: Maximum integration", "", &PID4AxisConfig::YAW_I_LIMIT)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_I_LIMIT", "double", 0, "YAW: Maximum integration", "", &PID4AxisConfig::YAW_I_LIMIT)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.YAW_MIN_ACTUATION = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.YAW_MIN_ACTUATION = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.YAW_MIN_ACTUATION = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_MIN_ACTUATION", "double", 0, "YAW: Minimum actuation", "", &PID4AxisConfig::YAW_MIN_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_MIN_ACTUATION", "double", 0, "YAW: Minimum actuation", "", &PID4AxisConfig::YAW_MIN_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.YAW_MAX_ACTUATION = -100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.YAW_MAX_ACTUATION = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.YAW_MAX_ACTUATION = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_MAX_ACTUATION", "double", 0, "YAW: Maximum actuation", "", &PID4AxisConfig::YAW_MAX_ACTUATION)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PID4AxisConfig::AbstractParamDescriptionConstPtr(new PID4AxisConfig::ParamDescription<double>("YAW_MAX_ACTUATION", "double", 0, "YAW: Maximum actuation", "", &PID4AxisConfig::YAW_MAX_ACTUATION)));
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(PID4AxisConfig::AbstractGroupDescriptionConstPtr(new PID4AxisConfig::GroupDescription<PID4AxisConfig::DEFAULT, PID4AxisConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<PID4AxisConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<PID4AxisConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PID4AxisConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PID4AxisConfig __max__;
    PID4AxisConfig __min__;
    PID4AxisConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PID4AxisConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PID4AxisConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PID4AxisConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const PID4AxisConfig &PID4AxisConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const PID4AxisConfig &PID4AxisConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const PID4AxisConfig &PID4AxisConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<PID4AxisConfig::AbstractParamDescriptionConstPtr> &PID4AxisConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PID4AxisConfig::AbstractGroupDescriptionConstPtr> &PID4AxisConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PID4AxisConfigStatics *PID4AxisConfig::__get_statics__()
  {
    const static PID4AxisConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PID4AxisConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __PID4AXISRECONFIGURATOR_H__
