//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the proc_control package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __proc_control__THRUSTERCONFIG_H__
#define __proc_control__THRUSTERCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace proc_control
{
  class ThrusterConfigStatics;
  
  class ThrusterConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(ThrusterConfig &config, const ThrusterConfig &max, const ThrusterConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ThrusterConfig &config1, const ThrusterConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ThrusterConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ThrusterConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ThrusterConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ThrusterConfig &config) const = 0;
      virtual void getValue(const ThrusterConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T ThrusterConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (ThrusterConfig::* field);

      virtual void clamp(ThrusterConfig &config, const ThrusterConfig &max, const ThrusterConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ThrusterConfig &config1, const ThrusterConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ThrusterConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ThrusterConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ThrusterConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ThrusterConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ThrusterConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ThrusterConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ThrusterConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<ThrusterConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ThrusterConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Port_X"==(*_i)->name){Port_X = boost::any_cast<double>(val);}
        if("Port_Y"==(*_i)->name){Port_Y = boost::any_cast<double>(val);}
        if("Port_Z"==(*_i)->name){Port_Z = boost::any_cast<double>(val);}
        if("Port_YAW"==(*_i)->name){Port_YAW = boost::any_cast<double>(val);}
        if("Port_PITCH"==(*_i)->name){Port_PITCH = boost::any_cast<double>(val);}
        if("Port_ROLL"==(*_i)->name){Port_ROLL = boost::any_cast<double>(val);}
        if("Starboard_X"==(*_i)->name){Starboard_X = boost::any_cast<double>(val);}
        if("Starboard_Y"==(*_i)->name){Starboard_Y = boost::any_cast<double>(val);}
        if("Starboard_Z"==(*_i)->name){Starboard_Z = boost::any_cast<double>(val);}
        if("Starboard_YAW"==(*_i)->name){Starboard_YAW = boost::any_cast<double>(val);}
        if("Starboard_PITCH"==(*_i)->name){Starboard_PITCH = boost::any_cast<double>(val);}
        if("Starboard_ROLL"==(*_i)->name){Starboard_ROLL = boost::any_cast<double>(val);}
        if("Front_Depth_X"==(*_i)->name){Front_Depth_X = boost::any_cast<double>(val);}
        if("Front_Depth_Y"==(*_i)->name){Front_Depth_Y = boost::any_cast<double>(val);}
        if("Front_Depth_Z"==(*_i)->name){Front_Depth_Z = boost::any_cast<double>(val);}
        if("Front_Depth_YAW"==(*_i)->name){Front_Depth_YAW = boost::any_cast<double>(val);}
        if("Front_Depth_PITCH"==(*_i)->name){Front_Depth_PITCH = boost::any_cast<double>(val);}
        if("Front_Depth_ROLL"==(*_i)->name){Front_Depth_ROLL = boost::any_cast<double>(val);}
        if("Back_Depth_X"==(*_i)->name){Back_Depth_X = boost::any_cast<double>(val);}
        if("Back_Depth_Y"==(*_i)->name){Back_Depth_Y = boost::any_cast<double>(val);}
        if("Back_Depth_Z"==(*_i)->name){Back_Depth_Z = boost::any_cast<double>(val);}
        if("Back_Depth_YAW"==(*_i)->name){Back_Depth_YAW = boost::any_cast<double>(val);}
        if("Back_Depth_PITCH"==(*_i)->name){Back_Depth_PITCH = boost::any_cast<double>(val);}
        if("Back_Depth_ROLL"==(*_i)->name){Back_Depth_ROLL = boost::any_cast<double>(val);}
        if("Front_Heading_X"==(*_i)->name){Front_Heading_X = boost::any_cast<double>(val);}
        if("Front_Heading_Y"==(*_i)->name){Front_Heading_Y = boost::any_cast<double>(val);}
        if("Front_Heading_Z"==(*_i)->name){Front_Heading_Z = boost::any_cast<double>(val);}
        if("Front_Heading_YAW"==(*_i)->name){Front_Heading_YAW = boost::any_cast<double>(val);}
        if("Front_Heading_PITCH"==(*_i)->name){Front_Heading_PITCH = boost::any_cast<double>(val);}
        if("Front_Heading_ROLL"==(*_i)->name){Front_Heading_ROLL = boost::any_cast<double>(val);}
        if("Back_Heading_X"==(*_i)->name){Back_Heading_X = boost::any_cast<double>(val);}
        if("Back_Heading_Y"==(*_i)->name){Back_Heading_Y = boost::any_cast<double>(val);}
        if("Back_Heading_Z"==(*_i)->name){Back_Heading_Z = boost::any_cast<double>(val);}
        if("Back_Heading_YAW"==(*_i)->name){Back_Heading_YAW = boost::any_cast<double>(val);}
        if("Back_Heading_PITCH"==(*_i)->name){Back_Heading_PITCH = boost::any_cast<double>(val);}
        if("Back_Heading_ROLL"==(*_i)->name){Back_Heading_ROLL = boost::any_cast<double>(val);}
      }
    }

    double Port_X;
double Port_Y;
double Port_Z;
double Port_YAW;
double Port_PITCH;
double Port_ROLL;
double Starboard_X;
double Starboard_Y;
double Starboard_Z;
double Starboard_YAW;
double Starboard_PITCH;
double Starboard_ROLL;
double Front_Depth_X;
double Front_Depth_Y;
double Front_Depth_Z;
double Front_Depth_YAW;
double Front_Depth_PITCH;
double Front_Depth_ROLL;
double Back_Depth_X;
double Back_Depth_Y;
double Back_Depth_Z;
double Back_Depth_YAW;
double Back_Depth_PITCH;
double Back_Depth_ROLL;
double Front_Heading_X;
double Front_Heading_Y;
double Front_Heading_Z;
double Front_Heading_YAW;
double Front_Heading_PITCH;
double Front_Heading_ROLL;
double Back_Heading_X;
double Back_Heading_Y;
double Back_Heading_Z;
double Back_Heading_YAW;
double Back_Heading_PITCH;
double Back_Heading_ROLL;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Port_X;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Port_Y;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Port_Z;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Port_YAW;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Port_PITCH;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Port_ROLL;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Starboard_X;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Starboard_Y;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Starboard_Z;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Starboard_YAW;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Starboard_PITCH;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Starboard_ROLL;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Depth_X;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Depth_Y;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Depth_Z;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Depth_YAW;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Depth_PITCH;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Depth_ROLL;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Depth_X;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Depth_Y;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Depth_Z;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Depth_YAW;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Depth_PITCH;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Depth_ROLL;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Heading_X;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Heading_Y;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Heading_Z;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Heading_YAW;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Heading_PITCH;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Front_Heading_ROLL;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Heading_X;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Heading_Y;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Heading_Z;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Heading_YAW;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Heading_PITCH;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Back_Heading_ROLL;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ThrusterConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ThrusterConfig &__max__ = __getMax__();
      const ThrusterConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ThrusterConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ThrusterConfig &__getDefault__();
    static const ThrusterConfig &__getMax__();
    static const ThrusterConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const ThrusterConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void ThrusterConfig::ParamDescription<std::string>::clamp(ThrusterConfig &config, const ThrusterConfig &max, const ThrusterConfig &min) const
  {
    return;
  }

  class ThrusterConfigStatics
  {
    friend class ThrusterConfig;
    
    ThrusterConfigStatics()
    {
ThrusterConfig::GroupDescription<ThrusterConfig::DEFAULT, ThrusterConfig> Default("Default", "", 0, 0, true, &ThrusterConfig::groups);
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Port_X = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Port_X = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Port_X = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_X", "double", 0, "Port: The force in X", "", &ThrusterConfig::Port_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_X", "double", 0, "Port: The force in X", "", &ThrusterConfig::Port_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Port_Y = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Port_Y = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Port_Y = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_Y", "double", 0, "Port: The force in Y", "", &ThrusterConfig::Port_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_Y", "double", 0, "Port: The force in Y", "", &ThrusterConfig::Port_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Port_Z = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Port_Z = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Port_Z = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_Z", "double", 0, "Port: The force in Z", "", &ThrusterConfig::Port_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_Z", "double", 0, "Port: The force in Z", "", &ThrusterConfig::Port_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Port_YAW = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Port_YAW = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Port_YAW = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_YAW", "double", 0, "Port: The force in YAW", "", &ThrusterConfig::Port_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_YAW", "double", 0, "Port: The force in YAW", "", &ThrusterConfig::Port_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Port_PITCH = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Port_PITCH = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Port_PITCH = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_PITCH", "double", 0, "Port: The force in PITCH", "", &ThrusterConfig::Port_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_PITCH", "double", 0, "Port: The force in PITCH", "", &ThrusterConfig::Port_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Port_ROLL = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Port_ROLL = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Port_ROLL = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_ROLL", "double", 0, "Port: The force in ROLL", "", &ThrusterConfig::Port_ROLL)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Port_ROLL", "double", 0, "Port: The force in ROLL", "", &ThrusterConfig::Port_ROLL)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Starboard_X = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Starboard_X = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Starboard_X = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_X", "double", 0, "Starboard: The force in X", "", &ThrusterConfig::Starboard_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_X", "double", 0, "Starboard: The force in X", "", &ThrusterConfig::Starboard_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Starboard_Y = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Starboard_Y = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Starboard_Y = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_Y", "double", 0, "Starboard: The force in Y", "", &ThrusterConfig::Starboard_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_Y", "double", 0, "Starboard: The force in Y", "", &ThrusterConfig::Starboard_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Starboard_Z = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Starboard_Z = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Starboard_Z = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_Z", "double", 0, "Starboard: The force in Z", "", &ThrusterConfig::Starboard_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_Z", "double", 0, "Starboard: The force in Z", "", &ThrusterConfig::Starboard_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Starboard_YAW = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Starboard_YAW = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Starboard_YAW = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_YAW", "double", 0, "Starboard: The force in YAW", "", &ThrusterConfig::Starboard_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_YAW", "double", 0, "Starboard: The force in YAW", "", &ThrusterConfig::Starboard_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Starboard_PITCH = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Starboard_PITCH = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Starboard_PITCH = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_PITCH", "double", 0, "Starboard: The force in PITCH", "", &ThrusterConfig::Starboard_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_PITCH", "double", 0, "Starboard: The force in PITCH", "", &ThrusterConfig::Starboard_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Starboard_ROLL = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Starboard_ROLL = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Starboard_ROLL = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_ROLL", "double", 0, "Starboard: The force in ROLL", "", &ThrusterConfig::Starboard_ROLL)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Starboard_ROLL", "double", 0, "Starboard: The force in ROLL", "", &ThrusterConfig::Starboard_ROLL)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Depth_X = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Depth_X = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Depth_X = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_X", "double", 0, "Front_Depth: The force in X", "", &ThrusterConfig::Front_Depth_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_X", "double", 0, "Front_Depth: The force in X", "", &ThrusterConfig::Front_Depth_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Depth_Y = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Depth_Y = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Depth_Y = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_Y", "double", 0, "Front_Depth: The force in Y", "", &ThrusterConfig::Front_Depth_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_Y", "double", 0, "Front_Depth: The force in Y", "", &ThrusterConfig::Front_Depth_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Depth_Z = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Depth_Z = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Depth_Z = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_Z", "double", 0, "Front_Depth: The force in Z", "", &ThrusterConfig::Front_Depth_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_Z", "double", 0, "Front_Depth: The force in Z", "", &ThrusterConfig::Front_Depth_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Depth_YAW = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Depth_YAW = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Depth_YAW = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_YAW", "double", 0, "Front_Depth: The force in YAW", "", &ThrusterConfig::Front_Depth_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_YAW", "double", 0, "Front_Depth: The force in YAW", "", &ThrusterConfig::Front_Depth_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Depth_PITCH = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Depth_PITCH = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Depth_PITCH = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_PITCH", "double", 0, "Front_Depth: The force in PITCH", "", &ThrusterConfig::Front_Depth_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_PITCH", "double", 0, "Front_Depth: The force in PITCH", "", &ThrusterConfig::Front_Depth_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Depth_ROLL = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Depth_ROLL = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Depth_ROLL = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_ROLL", "double", 0, "Front_Depth: The force in ROLL", "", &ThrusterConfig::Front_Depth_ROLL)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Depth_ROLL", "double", 0, "Front_Depth: The force in ROLL", "", &ThrusterConfig::Front_Depth_ROLL)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Depth_X = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Depth_X = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Depth_X = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_X", "double", 0, "Back_Depth: The force in X", "", &ThrusterConfig::Back_Depth_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_X", "double", 0, "Back_Depth: The force in X", "", &ThrusterConfig::Back_Depth_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Depth_Y = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Depth_Y = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Depth_Y = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_Y", "double", 0, "Back_Depth: The force in Y", "", &ThrusterConfig::Back_Depth_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_Y", "double", 0, "Back_Depth: The force in Y", "", &ThrusterConfig::Back_Depth_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Depth_Z = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Depth_Z = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Depth_Z = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_Z", "double", 0, "Back_Depth: The force in Z", "", &ThrusterConfig::Back_Depth_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_Z", "double", 0, "Back_Depth: The force in Z", "", &ThrusterConfig::Back_Depth_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Depth_YAW = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Depth_YAW = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Depth_YAW = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_YAW", "double", 0, "Back_Depth: The force in YAW", "", &ThrusterConfig::Back_Depth_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_YAW", "double", 0, "Back_Depth: The force in YAW", "", &ThrusterConfig::Back_Depth_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Depth_PITCH = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Depth_PITCH = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Depth_PITCH = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_PITCH", "double", 0, "Back_Depth: The force in PITCH", "", &ThrusterConfig::Back_Depth_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_PITCH", "double", 0, "Back_Depth: The force in PITCH", "", &ThrusterConfig::Back_Depth_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Depth_ROLL = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Depth_ROLL = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Depth_ROLL = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_ROLL", "double", 0, "Back_Depth: The force in ROLL", "", &ThrusterConfig::Back_Depth_ROLL)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Depth_ROLL", "double", 0, "Back_Depth: The force in ROLL", "", &ThrusterConfig::Back_Depth_ROLL)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Heading_X = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Heading_X = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Heading_X = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_X", "double", 0, "Front_Heading: The force in X", "", &ThrusterConfig::Front_Heading_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_X", "double", 0, "Front_Heading: The force in X", "", &ThrusterConfig::Front_Heading_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Heading_Y = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Heading_Y = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Heading_Y = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_Y", "double", 0, "Front_Heading: The force in Y", "", &ThrusterConfig::Front_Heading_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_Y", "double", 0, "Front_Heading: The force in Y", "", &ThrusterConfig::Front_Heading_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Heading_Z = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Heading_Z = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Heading_Z = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_Z", "double", 0, "Front_Heading: The force in Z", "", &ThrusterConfig::Front_Heading_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_Z", "double", 0, "Front_Heading: The force in Z", "", &ThrusterConfig::Front_Heading_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Heading_YAW = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Heading_YAW = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Heading_YAW = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_YAW", "double", 0, "Front_Heading: The force in YAW", "", &ThrusterConfig::Front_Heading_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_YAW", "double", 0, "Front_Heading: The force in YAW", "", &ThrusterConfig::Front_Heading_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Heading_PITCH = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Heading_PITCH = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Heading_PITCH = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_PITCH", "double", 0, "Front_Heading: The force in PITCH", "", &ThrusterConfig::Front_Heading_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_PITCH", "double", 0, "Front_Heading: The force in PITCH", "", &ThrusterConfig::Front_Heading_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Front_Heading_ROLL = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Front_Heading_ROLL = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Front_Heading_ROLL = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_ROLL", "double", 0, "Front_Heading: The force in ROLL", "", &ThrusterConfig::Front_Heading_ROLL)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Front_Heading_ROLL", "double", 0, "Front_Heading: The force in ROLL", "", &ThrusterConfig::Front_Heading_ROLL)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Heading_X = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Heading_X = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Heading_X = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_X", "double", 0, "Back_Heading: The force in X", "", &ThrusterConfig::Back_Heading_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_X", "double", 0, "Back_Heading: The force in X", "", &ThrusterConfig::Back_Heading_X)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Heading_Y = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Heading_Y = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Heading_Y = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_Y", "double", 0, "Back_Heading: The force in Y", "", &ThrusterConfig::Back_Heading_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_Y", "double", 0, "Back_Heading: The force in Y", "", &ThrusterConfig::Back_Heading_Y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Heading_Z = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Heading_Z = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Heading_Z = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_Z", "double", 0, "Back_Heading: The force in Z", "", &ThrusterConfig::Back_Heading_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_Z", "double", 0, "Back_Heading: The force in Z", "", &ThrusterConfig::Back_Heading_Z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Heading_YAW = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Heading_YAW = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Heading_YAW = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_YAW", "double", 0, "Back_Heading: The force in YAW", "", &ThrusterConfig::Back_Heading_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_YAW", "double", 0, "Back_Heading: The force in YAW", "", &ThrusterConfig::Back_Heading_YAW)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Heading_PITCH = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Heading_PITCH = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Heading_PITCH = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_PITCH", "double", 0, "Back_Heading: The force in PITCH", "", &ThrusterConfig::Back_Heading_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_PITCH", "double", 0, "Back_Heading: The force in PITCH", "", &ThrusterConfig::Back_Heading_PITCH)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Back_Heading_ROLL = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Back_Heading_ROLL = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Back_Heading_ROLL = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_ROLL", "double", 0, "Back_Heading: The force in ROLL", "", &ThrusterConfig::Back_Heading_ROLL)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ThrusterConfig::AbstractParamDescriptionConstPtr(new ThrusterConfig::ParamDescription<double>("Back_Heading_ROLL", "double", 0, "Back_Heading: The force in ROLL", "", &ThrusterConfig::Back_Heading_ROLL)));
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(ThrusterConfig::AbstractGroupDescriptionConstPtr(new ThrusterConfig::GroupDescription<ThrusterConfig::DEFAULT, ThrusterConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<ThrusterConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<ThrusterConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ThrusterConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ThrusterConfig __max__;
    ThrusterConfig __min__;
    ThrusterConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ThrusterConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ThrusterConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ThrusterConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const ThrusterConfig &ThrusterConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const ThrusterConfig &ThrusterConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const ThrusterConfig &ThrusterConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<ThrusterConfig::AbstractParamDescriptionConstPtr> &ThrusterConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ThrusterConfig::AbstractGroupDescriptionConstPtr> &ThrusterConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ThrusterConfigStatics *ThrusterConfig::__get_statics__()
  {
    const static ThrusterConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ThrusterConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __THRUSTERRECONFIGURATOR_H__
